Default: &defaults
  database: oqs.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: oqs_test.sqlite3
  <<: *defaults

Staging:
  database: oqs_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: oqs_production.sqlite3
  poolsize: 100
  <<: *defaults
